// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: envelope.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageFlags 消息标志位
type MessageFlags int32

const (
	MessageFlags_MESSAGE_FLAGS_NONE       MessageFlags = 0 // 无标志
	MessageFlags_MESSAGE_FLAGS_COMPRESSED MessageFlags = 1 // 已压缩
	MessageFlags_MESSAGE_FLAGS_ENCRYPTED  MessageFlags = 2 // 已加密
)

// Enum value maps for MessageFlags.
var (
	MessageFlags_name = map[int32]string{
		0: "MESSAGE_FLAGS_NONE",
		1: "MESSAGE_FLAGS_COMPRESSED",
		2: "MESSAGE_FLAGS_ENCRYPTED",
	}
	MessageFlags_value = map[string]int32{
		"MESSAGE_FLAGS_NONE":       0,
		"MESSAGE_FLAGS_COMPRESSED": 1,
		"MESSAGE_FLAGS_ENCRYPTED":  2,
	}
)

func (x MessageFlags) Enum() *MessageFlags {
	p := new(MessageFlags)
	*p = x
	return p
}

func (x MessageFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageFlags) Type() protoreflect.EnumType {
	return &file_envelope_proto_enumTypes[0]
}

func (x MessageFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFlags.Descriptor instead.
func (MessageFlags) EnumDescriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

// MessageHeader 消息头
type MessageHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            uint32                 `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`                    // 操作码
	SeqId         uint64                 `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"` // 序列号
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                // 载荷大小
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`              // 标志位
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      // 时间戳
	Sign          []byte                 `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`                 // 签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *MessageHeader) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *MessageHeader) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageHeader) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *MessageHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageHeader) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

// Envelope 消息信封
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *MessageHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`   // 消息头
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 载荷
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\x06common\"\x92\x01\n" +
	"\rMessageHeader\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\rR\x02op\x12\x15\n" +
	"\x06seq_id\x18\x02 \x01(\x04R\x05seqId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04sign\x18\x06 \x01(\fR\x04sign\"S\n" +
	"\bEnvelope\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.common.MessageHeaderR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload*a\n" +
	"\fMessageFlags\x12\x16\n" +
	"\x12MESSAGE_FLAGS_NONE\x10\x00\x12\x1c\n" +
	"\x18MESSAGE_FLAGS_COMPRESSED\x10\x01\x12\x1b\n" +
	"\x17MESSAGE_FLAGS_ENCRYPTED\x10\x02B5Z3github.com/lk2023060901/xiaojia-proto-common;commonb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(MessageFlags)(0),     // 0: common.MessageFlags
	(*MessageHeader)(nil), // 1: common.MessageHeader
	(*Envelope)(nil),      // 2: common.Envelope
}
var file_envelope_proto_depIdxs = []int32{
	1, // 0: common.Envelope.header:type_name -> common.MessageHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		EnumInfos:         file_envelope_proto_enumTypes,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
