// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/login.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginType 定义登录/认证类型
type LoginType int32

const (
	// 默认值 (无效)
	LoginType_LOGIN_TYPE_NONE LoginType = 0
	// 本地测试登录 (xlsx/config)
	LoginType_LOGIN_TYPE_LOCAL LoginType = 1
	// 内部账号密码登录
	LoginType_LOGIN_TYPE_INTERNAL LoginType = 2
	// 抖音平台登录
	LoginType_LOGIN_TYPE_DOUYIN LoginType = 3
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LOGIN_TYPE_NONE",
		1: "LOGIN_TYPE_LOCAL",
		2: "LOGIN_TYPE_INTERNAL",
		3: "LOGIN_TYPE_DOUYIN",
	}
	LoginType_value = map[string]int32{
		"LOGIN_TYPE_NONE":     0,
		"LOGIN_TYPE_LOCAL":    1,
		"LOGIN_TYPE_INTERNAL": 2,
		"LOGIN_TYPE_DOUYIN":   3,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_login_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_proto_login_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_proto_login_proto_rawDescGZIP(), []int{0}
}

var File_proto_login_proto protoreflect.FileDescriptor

const file_proto_login_proto_rawDesc = "" +
	"\n" +
	"\x11proto/login.proto\x12\x06common*f\n" +
	"\tLoginType\x12\x13\n" +
	"\x0fLOGIN_TYPE_NONE\x10\x00\x12\x14\n" +
	"\x10LOGIN_TYPE_LOCAL\x10\x01\x12\x17\n" +
	"\x13LOGIN_TYPE_INTERNAL\x10\x02\x12\x15\n" +
	"\x11LOGIN_TYPE_DOUYIN\x10\x03B5Z3github.com/lk2023060901/xiaojia-proto-common;commonb\x06proto3"

var (
	file_proto_login_proto_rawDescOnce sync.Once
	file_proto_login_proto_rawDescData []byte
)

func file_proto_login_proto_rawDescGZIP() []byte {
	file_proto_login_proto_rawDescOnce.Do(func() {
		file_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)))
	})
	return file_proto_login_proto_rawDescData
}

var file_proto_login_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_login_proto_goTypes = []any{
	(LoginType)(0), // 0: common.LoginType
}
var file_proto_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_login_proto_init() }
func file_proto_login_proto_init() {
	if File_proto_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_login_proto_rawDesc), len(file_proto_login_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_login_proto_goTypes,
		DependencyIndexes: file_proto_login_proto_depIdxs,
		EnumInfos:         file_proto_login_proto_enumTypes,
	}.Build()
	File_proto_login_proto = out.File
	file_proto_login_proto_goTypes = nil
	file_proto_login_proto_depIdxs = nil
}
