// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: login.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest 登录请求
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录类型
	LoginType LoginType `protobuf:"varint,1,opt,name=login_type,json=loginType,proto3,enum=common.LoginType" json:"login_type,omitempty"`
	// 主播 UUID
	AnchorUuid string `protobuf:"bytes,2,opt,name=anchor_uuid,json=anchorUuid,proto3" json:"anchor_uuid,omitempty"`
	// 由 Douyin Webcast / OpenAPI 下发的直播 token。
	// 服务端通过 https://webcast.bytedance.com/api/webcastmate/info 等接口
	// 使用该 token 获取直播间信息并完成环境校验。
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// 设备 / 运行环境的额外元数据（可选）
	DeviceMetadata map[string]string `protobuf:"bytes,4,rep,name=device_metadata,json=deviceMetadata,proto3" json:"device_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLoginType() LoginType {
	if x != nil {
		return x.LoginType
	}
	return LoginType_LOGIN_TYPE_NONE
}

func (x *LoginRequest) GetAnchorUuid() string {
	if x != nil {
		return x.AnchorUuid
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetDeviceMetadata() map[string]string {
	if x != nil {
		return x.DeviceMetadata
	}
	return nil
}

// LoginResponse 登录响应
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码
	Code          ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_ERR_SUCCESS
}

var File_login_proto protoreflect.FileDescriptor

const file_login_proto_rawDesc = "" +
	"\n" +
	"\vlogin.proto\x12\x06common\x1a\x10login_type.proto\x1a\x0eerr_code.proto\"\x8d\x02\n" +
	"\fLoginRequest\x120\n" +
	"\n" +
	"login_type\x18\x01 \x01(\x0e2\x11.common.LoginTypeR\tloginType\x12\x1f\n" +
	"\vanchor_uuid\x18\x02 \x01(\tR\n" +
	"anchorUuid\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12Q\n" +
	"\x0fdevice_metadata\x18\x04 \x03(\v2(.common.LoginRequest.DeviceMetadataEntryR\x0edeviceMetadata\x1aA\n" +
	"\x13DeviceMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\rLoginResponse\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.common.ErrCodeR\x04codeB5Z3github.com/lk2023060901/xiaojia-proto-common;commonb\x06proto3"

var (
	file_login_proto_rawDescOnce sync.Once
	file_login_proto_rawDescData []byte
)

func file_login_proto_rawDescGZIP() []byte {
	file_login_proto_rawDescOnce.Do(func() {
		file_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)))
	})
	return file_login_proto_rawDescData
}

var file_login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_login_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: common.LoginRequest
	(*LoginResponse)(nil), // 1: common.LoginResponse
	nil,                   // 2: common.LoginRequest.DeviceMetadataEntry
	(LoginType)(0),        // 3: common.LoginType
	(ErrCode)(0),          // 4: common.ErrCode
}
var file_login_proto_depIdxs = []int32{
	3, // 0: common.LoginRequest.login_type:type_name -> common.LoginType
	2, // 1: common.LoginRequest.device_metadata:type_name -> common.LoginRequest.DeviceMetadataEntry
	4, // 2: common.LoginResponse.code:type_name -> common.ErrCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_login_proto_init() }
func file_login_proto_init() {
	if File_login_proto != nil {
		return
	}
	file_login_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_proto_rawDesc), len(file_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_proto_goTypes,
		DependencyIndexes: file_login_proto_depIdxs,
		MessageInfos:      file_login_proto_msgTypes,
	}.Build()
	File_login_proto = out.File
	file_login_proto_goTypes = nil
	file_login_proto_depIdxs = nil
}
